/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elearning.gui;

import elearning.database.DataStore;
import elearning.model.Dosen;
import elearning.model.KRS;
import elearning.model.Mahasiswa;
import elearning.model.MataKuliah;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class KRS_Form extends javax.swing.JFrame {

    private DataStore ds = DataStore.getInstance();
    private DefaultTableModel model;
    private int idKRSCounter = 0;
    /**
     * Creates new form KRS_Form
     */
    public KRS_Form() {
        initComponents();
        setLocationRelativeTo(null); 

        cmbMahasiswa.removeAllItems();
        for (int i = 0; i < ds.getJumlahMhs(); i++) {
        Mahasiswa m = ds.getMahasiswas()[i];
        cmbMahasiswa.addItem(m.getNim() + " - " + m.getNama());
    }

        cmbMatakuliah.removeAllItems();
        for (int i = 0; i < ds.getJumlahMK(); i++) {
        MataKuliah mk = ds.getMataKuliahs()[i];
        cmbMatakuliah.addItem(mk.getKodeMK() + " - " + mk.getNamaMK()
            + " (" + mk.getSks() + " SKS)");
    }

        cmbDosen.removeAllItems();
        for (int i = 0; i < ds.getJumlahDosen(); i++) {
        Dosen d = ds.getDosens()[i];
        cmbDosen.addItem(d.getKodeDosen() + " - " + d.getNama());
    }

        // ── Setup tabel ───────────────────────────────────────────
        model = new DefaultTableModel(
        new String[]{"ID KRS","Mahasiswa","Mata Kuliah","SKS","Dosen","Semester"}, 0
    );
        tblKRS.setModel(model);
        refreshTable();

         // ── Setup progress bar ────────────────────────────────────
         progressSKS.setMinimum(0);
         progressSKS.setMaximum(24);
         progressSKS.setValue(0);
         progressSKS.setStringPainted(true); // tampilkan teks di dalam bar
         progressSKS.setString("0 / 24 SKS");

         // ── Update SKS saat mahasiswa diganti ─────────────────────
         cmbMahasiswa.addActionListener(e -> updateSKS());
         updateSKS(); // tampilkan awal

         // ── Klik baris tabel ──────────────────────────────────────
         tblKRS.getSelectionModel().addListSelectionListener(e -> {
         int row = tblKRS.getSelectedRow();
         if (row >= 0) {
         // opsional: highlight baris yang dipilih
        }
    });
    }
    
        private void updateSKS() {
        DataStore ds = DataStore.getInstance();
        int idx = cmbMahasiswa.getSelectedIndex();

        if (idx < 0 || idx >= ds.getJumlahMhs()) return;

        String nim   = ds.getMahasiswas()[idx].getNim();
        int total    = ds.getTotalSKS(nim);
        int sisa     = 24 - total;

        // Update label
        lblTotalSKS.setText("Total SKS: " + total + " / 24  (sisa " + sisa + " SKS)");

         // Update progress bar
         progressSKS.setValue(total);
         progressSKS.setString(total + " / 24 SKS");

         // Warna progress bar sesuai kondisi
         if (total >= 22) {
         // Hampir penuh — merah
         progressSKS.setForeground(new java.awt.Color(231, 76, 60));
         lblTotalSKS.setForeground(new java.awt.Color(231, 76, 60));
    } else if (total >= 18) {
         // Sedang — orange
         progressSKS.setForeground(new java.awt.Color(230, 126, 34));
         lblTotalSKS.setForeground(new java.awt.Color(230, 126, 34));
    } else {
         // Aman — biru
         progressSKS.setForeground(new java.awt.Color(46, 134, 171));
         lblTotalSKS.setForeground(new java.awt.Color(46, 134, 171));
    }
}
    
    private void refreshTable() {
    model.setRowCount(0);
    for (int i = 0; i < ds.getJumlahKRS(); i++) {
        KRS k = ds.getKrsList()[i];
        model.addRow(new Object[]{
            k.getIdKRS(),
            k.getMahasiswa().getNama(),
            k.getMataKuliah().getNamaMK(),
            k.getMataKuliah().getSks(),
            k.getDosen().getNama(),
            k.getSemester()
        });
    }
}
    
    private void clearForm() {
    if (cmbMahasiswa.getItemCount() > 0) cmbMahasiswa.setSelectedIndex(0);
    if (cmbMatakuliah.getItemCount() > 0) cmbMatakuliah.setSelectedIndex(0);
    if (cmbDosen.getItemCount() > 0) cmbDosen.setSelectedIndex(0);
    tblKRS.clearSelection();
    updateSKS();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbMataKuliah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbMahasiswa = new javax.swing.JComboBox<>();
        cmbMatakuliah = new javax.swing.JComboBox<>();
        cmbDosen = new javax.swing.JComboBox<>();
        txtSemester = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKRS = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTotalSKS = new javax.swing.JLabel();
        progressSKS = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D A T A   K R S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel1)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        cmbMataKuliah.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setText("Input Data :");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setText("Mahasiswa");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setText("Dosen");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel6.setText("Mata Kuliah");

        btnInput.setBackground(new java.awt.Color(51, 204, 0));
        btnInput.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnInput.setForeground(new java.awt.Color(255, 255, 255));
        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 204, 51));
        btnClear.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel8.setText("Semester");

        btnhapus.setBackground(new java.awt.Color(255, 0, 0));
        btnhapus.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cmbMataKuliahLayout = new javax.swing.GroupLayout(cmbMataKuliah);
        cmbMataKuliah.setLayout(cmbMataKuliahLayout);
        cmbMataKuliahLayout.setHorizontalGroup(
            cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                                    .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(0, 19, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cmbMataKuliahLayout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(btnInput)))
                                    .addGap(18, 18, 18)
                                    .addComponent(btnhapus)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClear)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnClose)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cmbMataKuliahLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSemester)
                                    .addComponent(cmbDosen, 0, 237, Short.MAX_VALUE)
                                    .addComponent(cmbMatakuliah, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMahasiswa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        cmbMataKuliahLayout.setVerticalGroup(
            cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbMatakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tblKRS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id KRS", "Mahasiswa", "Mata Kuliah", "SKS", "Dosen", "Semester"
            }
        ));
        jScrollPane1.setViewportView(tblKRS);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel7.setText("Data yang telah diinput :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setText("STATUS SKS MAHASISWA");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel9.setText("Total SkS :");

        lblTotalSKS.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        lblTotalSKS.setForeground(new java.awt.Color(51, 204, 0));
        lblTotalSKS.setText("-  ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)
                        .addComponent(lblTotalSKS))
                    .addComponent(jLabel2)
                    .addComponent(progressSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTotalSKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        DataStore ds = DataStore.getInstance();

    int idxMhs = cmbMahasiswa.getSelectedIndex();
    int idxMK  = cmbMatakuliah.getSelectedIndex();
    int idxDsn = cmbDosen.getSelectedIndex();

    if (idxMhs < 0 || idxMK < 0 || idxDsn < 0) {
        JOptionPane.showMessageDialog(this, "Semua field harus dipilih!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String semester = txtSemester.getText().trim();
    if (semester.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semester tidak boleh kosong!");
        return;
    }

    Mahasiswa  mhs   = ds.getMahasiswas()[idxMhs];
    MataKuliah mk    = ds.getMataKuliahs()[idxMK];
    Dosen      dosen = ds.getDosens()[idxDsn];

    // ── Validasi total SKS ≤ 24 ──────────────────────────────
    int sksSudah   = ds.getTotalSKS(mhs.getNim());
    int sksTambah  = mk.getSks();
    int totalNanti = sksSudah + sksTambah;

    if (totalNanti > 24) {
        // Animasikan progress bar ke merah dulu
        progressSKS.setValue(24);
        progressSKS.setForeground(new java.awt.Color(231, 76, 60));
        progressSKS.setString("MELEBIHI BATAS!");

        JOptionPane.showMessageDialog(this,
            "Batas SKS Terlampaui!\n\n"
            + "SKS sudah diambil    : " + sksSudah + " SKS\n"
            + "SKS mata kuliah ini  : " + sksTambah + " SKS\n"
            + "Total jika ditambah  : " + totalNanti + " SKS\n\n"
            + "Maksimal 24 SKS per semester.",
            "Batas SKS Terlampaui", JOptionPane.ERROR_MESSAGE);

        updateSKS(); // kembalikan progress bar ke kondisi asli
        return;
    }

    // ── Simpan KRS ────────────────────────────────────────────
    String idKRS = "KRS" + String.format("%03d", ++idKRSCounter);
    KRS krs = new KRS(idKRS, mhs, mk, dosen, semester);

    boolean berhasil = ds.tambahKRS(krs);
    if (berhasil) {
        refreshTable();
        updateSKS(); // update progress bar setelah input

        JOptionPane.showMessageDialog(this,
            "KRS berhasil disimpan!\n"
            + "Total SKS " + mhs.getNama() + " sekarang: "
            + ds.getTotalSKS(mhs.getNim()) + " SKS");
    } else {
        JOptionPane.showMessageDialog(this,
            "Data KRS penuh! Maksimal " + DataStore.MAX + " KRS.",
            "Penuh", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    if (cmbMahasiswa.getItemCount() > 0) cmbMahasiswa.setSelectedIndex(0);
    if (cmbMatakuliah.getItemCount() > 0) cmbMatakuliah.setSelectedIndex(0);
    if (cmbDosen.getItemCount() > 0) cmbDosen.setSelectedIndex(0);
    tblKRS.clearSelection();
    updateSKS(); // reset progress bar juga
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
         int row = tblKRS.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(this,
            "Pilih data KRS yang akan dihapus!",
            "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idKRS = model.getValueAt(row, 0).toString();
    String namaMhs = model.getValueAt(row, 1).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(this,
        "Hapus KRS " + idKRS + " milik " + namaMhs + "?\nData tidak bisa dikembalikan!",
        "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        boolean berhasil = ds.hapusKRS(idKRS);
        if (berhasil) {
            JOptionPane.showMessageDialog(this, "KRS berhasil dihapus!");
            refreshTable();
            updateSKS();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus KRS!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox<String> cmbDosen;
    private javax.swing.JComboBox<String> cmbMahasiswa;
    private javax.swing.JPanel cmbMataKuliah;
    private javax.swing.JComboBox<String> cmbMatakuliah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalSKS;
    private javax.swing.JProgressBar progressSKS;
    private javax.swing.JTable tblKRS;
    private javax.swing.JTextField txtSemester;
    // End of variables declaration//GEN-END:variables
}
