/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elearning.gui;
import elearning.database.DataStore;
import elearning.model.*;
import elearning.util.*;

public class MainMenuForm extends javax.swing.JFrame {

    private User currentUser; 
    
    public MainMenuForm(User user) {
        initComponents();
        setLocationRelativeTo(null); 
        this.currentUser = user;

    // Tampilkan info user
    lblWelcome.setText("Nama : " + user.getNamaUser()
        + " | Level: " + user.getLevel());

    // Batasi akses OPERATOR
    if (user.getLevel() == LevelUser.OPERATOR) {
        menuMaster.setEnabled(false);   // sembunyikan File Master
        menuAddUser.setVisible(false);  // sembunyikan Add User
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLABEL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuMahasiswa = new javax.swing.JMenuItem();
        menuDosen = new javax.swing.JMenuItem();
        menuMataKuliah = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuKRS = new javax.swing.JMenuItem();
        MenuNilai = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuAddUser = new javax.swing.JMenuItem();
        menuChangePass = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        JLABEL.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        JLABEL.setForeground(new java.awt.Color(255, 255, 255));
        JLABEL.setText("M A I N   M E N U");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(JLABEL)
                .addGap(187, 187, 187))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(JLABEL)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        lblWelcome.setBackground(new java.awt.Color(0, 0, 0));
        lblWelcome.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        lblWelcome.setText("-");

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 48)); // NOI18N
        jLabel1.setText("W E L C O M E");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblWelcome)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblWelcome)
                .addGap(151, 151, 151))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 390));

        menuMaster.setText("File Master");

        menuMahasiswa.setText("Mahasiswa");
        menuMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMahasiswaActionPerformed(evt);
            }
        });
        menuMaster.add(menuMahasiswa);

        menuDosen.setText("Dosen");
        menuDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDosenActionPerformed(evt);
            }
        });
        menuMaster.add(menuDosen);

        menuMataKuliah.setText("Mata Kuliah");
        menuMataKuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMataKuliahActionPerformed(evt);
            }
        });
        menuMaster.add(menuMataKuliah);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaction");

        menuKRS.setText("KRS");
        menuKRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKRSActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuKRS);

        MenuNilai.setText("Nilai");
        MenuNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNilaiActionPerformed(evt);
            }
        });
        menuTransaksi.add(MenuNilai);

        jMenuBar1.add(menuTransaksi);

        menuSettings.setText("Settings");

        menuAddUser.setText("Add User");
        menuAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddUserActionPerformed(evt);
            }
        });
        menuSettings.add(menuAddUser);

        menuChangePass.setText("Change Password");
        menuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChangePassActionPerformed(evt);
            }
        });
        menuSettings.add(menuChangePass);

        jMenuBar1.add(menuSettings);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMahasiswaActionPerformed
        Mahasiswa_Form form = new Mahasiswa_Form();
        form.setVisible(true);
    }//GEN-LAST:event_menuMahasiswaActionPerformed

    private void menuDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDosenActionPerformed
        Dosen_Form form = new Dosen_Form();
        form.setVisible(true);
    }//GEN-LAST:event_menuDosenActionPerformed

    private void menuMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMataKuliahActionPerformed
        MataKuliah_Form form = new MataKuliah_Form();
        form.setVisible(true);
    }//GEN-LAST:event_menuMataKuliahActionPerformed

    private void menuKRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKRSActionPerformed
        KRS_Form form = new KRS_Form();
        form.setVisible(true);
    }//GEN-LAST:event_menuKRSActionPerformed

    private void MenuNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNilaiActionPerformed
        Nilai_Form form = new Nilai_Form();
        form.setVisible(true);
    }//GEN-LAST:event_MenuNilaiActionPerformed

    private void menuAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddUserActionPerformed
        AddUserForm form = new AddUserForm();
        form.setVisible(true);
    }//GEN-LAST:event_menuAddUserActionPerformed

    private void menuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChangePassActionPerformed
        ChangePassword_Form form = new ChangePassword_Form(currentUser);
        form.setVisible(true);
    }//GEN-LAST:event_menuChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLABEL;
    private javax.swing.JMenuItem MenuNilai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem menuAddUser;
    private javax.swing.JMenuItem menuChangePass;
    private javax.swing.JMenuItem menuDosen;
    private javax.swing.JMenuItem menuKRS;
    private javax.swing.JMenuItem menuMahasiswa;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuMataKuliah;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
