/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package elearning.gui;

import elearning.database.DataStore;
import elearning.model.KRS;
import elearning.model.Nilai;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Nilai_Form extends javax.swing.JFrame {

    private DataStore ds = DataStore.getInstance();
    private DefaultTableModel model;
    
    public Nilai_Form() {
        initComponents();
        setLocationRelativeTo(null); 
        // Isi ComboBox KRS
        cmbKRS.removeAllItems();
    for (int i = 0; i < ds.getJumlahKRS(); i++) {
    KRS k = ds.getKrsList()[i];
    cmbKRS.addItem(k.getIdKRS() + " | "
        + k.getMahasiswa().getNama() + " | "
        + k.getMataKuliah().getNamaMK());
}

// Setup tabel
model = new DefaultTableModel(
    new String[]{"Mahasiswa","Mata Kuliah","UTS","Tugas","Absensi","UAS","Akhir","Huruf"}, 0
);
tblNilai.setModel(model);
refreshTable();
    }
    
    // ── Method Helper ──────────────────────────────────────────
private double parseInput(javax.swing.JTextField tf, String namaField) {
    String text = tf.getText().trim();
    if (text.isEmpty()) {
        throw new IllegalArgumentException("Nilai " + namaField + " tidak boleh kosong!");
    }
    try {
        double val = Double.parseDouble(text);
        if (val < 0 || val > 100) {
            throw new IllegalArgumentException(
                "Nilai " + namaField + " harus antara 0 - 100!");
        }
        return val;
    } catch (NumberFormatException e) {
        throw new IllegalArgumentException(
            "Nilai " + namaField + " harus berupa angka!");
    }
}

private void refreshTable() {
    model.setRowCount(0);
    for (int i = 0; i < ds.getJumlahNilai(); i++) {
        Nilai n = ds.getNilais()[i];
        model.addRow(new Object[]{
            n.getKrs().getMahasiswa().getNama(),
            n.getKrs().getMataKuliah().getNamaMK(),
            n.getNilaiUTS(),
            n.getNilaiTugas(),
            n.getNilaiAbsensi(),
            n.getNilaiUAS(),
            String.format("%.2f", n.getNilaiAkhir()),
            n.getNilaiHuruf()
        });
    }
}

private void hitungNilai() {
    try {
        double uts     = parseInput(txtUTS,     "UTS");
        double tugas   = parseInput(txtTugas,   "Tugas");
        double absensi = parseInput(txtAbsensi, "Absensi");
        double uas     = parseInput(txtUAS,     "UAS");

        int idx = cmbKRS.getSelectedIndex();
        if (idx < 0) return;
        KRS krs = ds.getKrsList()[idx];

        Nilai n = new Nilai(krs, uts, tugas, absensi, uas);

        lblNilaiAkhir.setText(String.format("%.2f", n.getNilaiAkhir()));
        lblNilaiHuruf.setText(n.getNilaiHuruf());

        switch (n.getNilaiHuruf()) {
            case "A": lblNilaiHuruf.setForeground(java.awt.Color.GREEN.darker()); break;
            case "B": lblNilaiHuruf.setForeground(java.awt.Color.BLUE); break;
            case "C": lblNilaiHuruf.setForeground(java.awt.Color.ORANGE); break;
            default:  lblNilaiHuruf.setForeground(java.awt.Color.RED); break;
        }

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(),
            "Input Tidak Valid", JOptionPane.ERROR_MESSAGE);
    }
}

private void clearForm() {
    txtUTS.setText("");
    txtTugas.setText("");
    txtAbsensi.setText("");
    txtUAS.setText("");
    lblNilaiAkhir.setText("—");
    lblNilaiHuruf.setText("—");
    lblNilaiHuruf.setForeground(java.awt.Color.BLACK);
    tblNilai.clearSelection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmbMataKuliah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbKRS = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtUTS = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtAbsensi = new javax.swing.JTextField();
        txtUAS = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnHitung1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNilaiAkhir = new javax.swing.JLabel();
        lblNilaiHuruf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("D A T A   N I L A I");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel1)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        cmbMataKuliah.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setText("Input Nilai :");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setText("Pilih KRS");

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setText("Tugas");

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel6.setText("UTS");

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel8.setText("Absensi");

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel10.setText("UAS");

        txtUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUASActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(51, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 204, 51));
        btnClear.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");

        btnClose.setBackground(new java.awt.Color(51, 51, 51));
        btnClose.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnHitung1.setBackground(new java.awt.Color(255, 0, 0));
        btnHitung1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        btnHitung1.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung1.setText("Hitung");
        btnHitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitung1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cmbMataKuliahLayout = new javax.swing.GroupLayout(cmbMataKuliah);
        cmbMataKuliah.setLayout(cmbMataKuliahLayout);
        cmbMataKuliahLayout.setHorizontalGroup(
            cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnHitung1))
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKRS, 0, 237, Short.MAX_VALUE)
                                    .addComponent(txtUTS)
                                    .addComponent(txtTugas)
                                    .addComponent(txtAbsensi)
                                    .addComponent(txtUAS)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cmbMataKuliahLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btnClear)
                                .addGap(12, 12, 12)
                                .addComponent(btnClose)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        cmbMataKuliahLayout.setVerticalGroup(
            cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmbMataKuliahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbKRS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmbMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mahasiswa", "Kode MK", "UTS", "Tugas", "Absensi", "UAS", "Nilai Akhir", "Huruf"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel7.setText("Data yang telah diinput :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setText("HASIL PERHITUNGAN :");

        jLabel9.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel9.setText("Nilai Akhir");

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel11.setText("Huruf");

        lblNilaiAkhir.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblNilaiAkhir.setForeground(new java.awt.Color(102, 102, 255));
        lblNilaiAkhir.setText("--");

        lblNilaiHuruf.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lblNilaiHuruf.setForeground(new java.awt.Color(51, 255, 51));
        lblNilaiHuruf.setText("--");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(lblNilaiAkhir))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblNilaiHuruf))
                            .addComponent(jLabel11))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNilaiAkhir)
                    .addComponent(lblNilaiHuruf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUASActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        hitungNilai();

    // Cek apakah sudah ada nilai (lblNilaiAkhir tidak "—")
    if (lblNilaiAkhir.getText().equals("—")) return;

    try {
        int idx = cmbKRS.getSelectedIndex();
        if (idx < 0) {
            JOptionPane.showMessageDialog(this, "Pilih KRS terlebih dahulu!");
            return;
        }

        KRS krs     = ds.getKrsList()[idx];
        double uts     = parseInput(txtUTS,     "UTS");
        double tugas   = parseInput(txtTugas,   "Tugas");
        double absensi = parseInput(txtAbsensi, "Absensi");
        double uas     = parseInput(txtUAS,     "UAS");

        Nilai n = new Nilai(krs, uts, tugas, absensi, uas);
        boolean berhasil = ds.tambahNilai(n);

        if (berhasil) {
            JOptionPane.showMessageDialog(this,
                "✅ Nilai berhasil disimpan!\n"
                + "Nilai Akhir : " + String.format("%.2f", n.getNilaiAkhir())
                + " (" + n.getNilaiHuruf() + ")");
            refreshTable();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this,
                "Data nilai penuh! Maksimal " + DataStore.MAX + " nilai.",
                "Penuh", JOptionPane.ERROR_MESSAGE);
        }

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Perbaiki input terlebih dahulu!",
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitung1ActionPerformed
        // TODO add your handling code here:
        try {
        double uts     = parseInput(txtUTS,     "UTS");
        double tugas   = parseInput(txtTugas,   "Tugas");
        double absensi = parseInput(txtAbsensi, "Absensi");
        double uas     = parseInput(txtUAS,     "UAS");

        // Hitung pakai rumus dari class Nilai
        int idx = cmbKRS.getSelectedIndex();
        if (idx < 0) return;
        KRS krs = ds.getKrsList()[idx];

        Nilai n = new Nilai(krs, uts, tugas, absensi, uas);

        lblNilaiAkhir.setText(String.format("%.2f", n.getNilaiAkhir()));
        lblNilaiHuruf.setText(n.getNilaiHuruf());

        // Warnai huruf sesuai grade
        switch (n.getNilaiHuruf()) {
            case "A": lblNilaiHuruf.setForeground(java.awt.Color.GREEN.darker()); break;
            case "B": lblNilaiHuruf.setForeground(java.awt.Color.BLUE); break;
            case "C": lblNilaiHuruf.setForeground(java.awt.Color.ORANGE); break;
            default : lblNilaiHuruf.setForeground(java.awt.Color.RED); break;
        }

    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Input Tidak Valid",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitung1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHitung1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbKRS;
    private javax.swing.JPanel cmbMataKuliah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNilaiAkhir;
    private javax.swing.JLabel lblNilaiHuruf;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtAbsensi;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUAS;
    private javax.swing.JTextField txtUTS;
    // End of variables declaration//GEN-END:variables
}
